"""add dsa and company expectations to jobs

Revision ID: 6dff268289fe
Revises: 831e7038716d
Create Date: 2026-09-16 18:51:07.039063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dff268289fe'
down_revision: Union[str, Sequence[str], None] = '831e7038716d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('dsa_level', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('dsa_reason', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('expectations', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('company_intel', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'company_intel')
    op.drop_column('jobs', 'expectations')
    op.drop_column('jobs', 'dsa_reason')
    op.drop_column('jobs', 'dsa_level')
    # ### end Alembic commands ###
